### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by lil-fox**

### CODE REVIEW

**Comment by sarunint** [comment]
I think you also need to update the `Versionfiles` submodules?

**Comment by dever-cube** [comment]
Actually, I already made pull request to it before make this one.

**Comment by sarunint** [comment]
Ah, I mean that if you visit https://github.com/dever-cube/AdvancementInfo/tree/fabric_1_19_4, you'll see that the `Versionfiles` submodule is still pointing towards https://github.com/gbl/Versionfiles/tree/e969dd9ab488fc152816454dc58d2a4e82c5a02a, which does not contains the 1.19.4 version information.

**Comment by sarunint** [comment]
(To be fair to you, we'll need to wait for gbl/Versionfiles#6 to be merged before updating this one.)

**Comment by RaptaG** [comment]
Resolves #31

**Comment by gbl** [comment]
Merged and published. Thank you for this; I haven't played Minecraft in a long time and not much time to update mods, so this really helped me to get a new version out.

**Pull request merged**
