### PR TITLE
Gui improvements & Configuration

### PR DESCRIPTION
**Pull request by Qendolin**
Improve GUI drawing and add cloth config support.

## Before
Before

## After
After

- Fixed overlapping draws
- Fixed incorrect uv coordiates
- Fixed search box position
- Improved vertical margins of criteria list
- Cloth Config / ModMenu integration
  - Info box width
  - Text colors

### CODE REVIEW

**Comment by gbl** [comment]
This looks very nice, and just in time before 1.18 comes out and everybody needs to update. Thank you!

**Comment by Qendolin** [comment]
I hope you can still build it on your end because I am not sure about the Versionfiles. (I am not familiar with git submodules)  
I added / changed
```
modmenu_version=2.0.11
cloth_config_version=5.0.38
```
in mcversion-1.17.1.properties

**Comment by gbl** [comment]
As I'm not including those mods in the jar, the exact versions don't matter, as long as there's no changes to the API. And I moved the cloth-config version directly to build.gradle (using 5.0.40), because I'm not using cloth-config in my other mods, so there's not much reason to have a version number in a submodule to share between mods.

Come to think about it, maybe I should include cloth-config, or AdvancementInfo won't work if people don't have cloth-config installed from somewhere else ...

**Comment by gbl** [comment]
Could you take a look at this? https://github.com/gbl/AdvancementInfo/issues/10

From what I've seen so far, you moved the AdvancementTabTypeMixin class from net.minecraft....advancement to de.guntram....advancement (I needed to have it in net.minecraft to be able to access the tab types), and added a public enum for the tab types instead. Unfortunately, this means the net.minecraft...AdvancementTabType class is visible in the sources now, so no refmap entry gets generated for them, which means the loader can't resolve the symbol, which means applying the mixin fails at load time, which means the patch to the calculation of the bottom and right positions doesn't get applied and they show where they would normally show.

Do you see another way of fixing that than reverting the move from net.minecraft ?

**Comment by Qendolin** [comment]
So sorry for breaking this, I wanted to test the tab position but I didn't have a way to get that many tabs 😓

**Comment by gbl** [comment]
Took me a while to get a setup with that many tabs enabled, too :) Thanks for the info about Fabulously Optimized, going to tell them. I released a version that undoes the class changes yesterday, so I hope they can fix that easily.

**Pull request merged**
