### PR TITLE
1.20 Update ✨

### PR DESCRIPTION
**Pull request by Wyne10**

### CODE REVIEW

**Comment by gitmeicl** [comment]
Thank you for this pr. Just builded it, it works well :)

**Comment by gbl** [comment]
Thank you for that. Will merge and make an official version over the weekend.

**Comment by BillyGalbreath** [comment]
it's weekend \o/

**Comment by gitmeicl** [comment]
@Wyne10, i've found that search bar doesn't work :(

**Comment by Wyne10** [comment]
> @Wyne10, i've found that search bar doesn't work :(

Thanks! Fixed it.

**Pull request closed without merging**
